# .github/workflows/imagepush.yml
name: Docker Image Build and Push

on:
 workflow_call:

jobs:
  image_push:
    runs-on: self-hosted
    env:
      DOCKER_IMAGE: sisi1234/petapp:${{ github.sha }}

    steps:
      - name: Build Docker Image
        run: |
           docker build -t ${{ env.DOCKER_IMAGE }} .
           docker save ${{ env.DOCKER_IMAGE }} > docker_image.tar


      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" |  docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker Image
        run: docker push ${{ env.DOCKER_IMAGE }}
