# .github/workflows/build.yml
name: Build

on: 
 workflow_call:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code 
        uses: actions/checkout@v3
        with:
         path: DevSecops_Pipeline


      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      
      - name: Build with Maven (explicit path)
        run: |
            export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
            export PATH=/opt/maven/bin:$JAVA_HOME/bin:$PATH
            /opt/maven/bin/mvn -v
            /opt/maven/bin/mvn clean install


      # - name: Upload Build Artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: jar
      #     path: target/*.jar
        
    #   - name: Configure JFrog CLI
    # token
    #     run: |
    #         jfrog config add my-artifactory --url=https://trial42aeja.jfrog.io --apikey=${{ secrets.JFROG_TOKEN }}
      - name: Configure JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        with:
          version: latest
        env:
          JF_URL: https://triallfbk5d.jfrog.io
          JF_ACCESS_TOKEN: ${{ secrets.JFROG_TOKEN }}
      - name: Upload JAR to JFrog
        run: |
           jf rt u "target/*.jar" " jf rt u "target/*.jar" "sisindrikilari1213-generic-local/"
     

