# .github/workflows/sonar.yml
name: Sonar Scan

on:
 workflow_call:

jobs:
  sonar:
    runs-on: self-hosted
    #needs: build  # Ensures Sonar runs after build succeeds
    steps:
      - name: SonarCloud Scan
        run: mvn sonar:sonar -Dsonar.projectKey=sisindrikilari_DevSecops_Pipeline -Dsonar.organization=sisindrikilari -Dsonar.host.url= https://sonarcloud.io -Dsonar.login=28ab27275057a104d3b6cc66d84f5a91d556cd6f
