# .github/workflows/test.yml
name: test
on:
  workflow_call:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Set JAVA_HOME and Maven in PATH
        run: |
          export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
          export PATH=/opt/maven/bin:$JAVA_HOME/bin:$PATH
          mvn -v

      - name: Run Unit Tests
        run: |
          export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
          export PATH=/opt/maven/bin:$JAVA_HOME/bin:$PATH
          mvn test


      # - name: Upload Test Results
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: test-results
      #     path: target/test-classes/TEST-*.xml
